### ISSUE TITLE
Shout out to the maintainers of this utility

### ISSUE THREAD

**Issue by picasso566** [SoftCircuits/FullTextSearchQuery#2]
I was searching for a long while now off and on for a reliable string to FullText parser and I finally found one! I was too busy to write my own and I was going down the path of using Antlr which was getting way over-complicated. 

Thank you guys so much! Your very concise library approaches the issue in a far simpler way and seems to work for me no matter the syntax and language.

**Comment by SoftCircuits** [comment]
Thanks!
